version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tu_password
      MYSQL_DATABASE: nombre_de_tu_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./inventory-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./inventory-dashboard:/app
    command: npm run dev
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: tu_password
      MYSQL_DATABASE: nombre_de_tu_db
    depends_on:
      - mysql

  frontend:
    build: ./Frontend-Inventory
    ports:
      - "5173:80"

volumes:
  mysql-data:

